title: Ning Li # your name (or website title) here
logo: "/images/IMG_5233.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  CS Graduate Student @ UPenn
  <br><br>
  CPA
  <br><br>
  <a href="https://www.linkedin.com/in/ningann-li/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
